version: '3.1'
services:
  web:
    image: odoo:13.0
    restart: always
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./odoo13:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    environment:
      - PASSWORD_FILE=/run/secrets/postgresql_password
    secrets:
      - postgresql_password
  db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgresql_password
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    secrets:
      - postgresql_password

secrets:
  postgresql_password:
    file: odoo_pg_pass
